### ISSUE TITLE
PSU 1.4.6: Error with PSCustomObjects after table refresh

### ISSUE THREAD

**Issue by JustinGrote** [ironmansoftware/powershell-universal-legacy#74]
#### Description
Related to #68 

When using Objects with UDTables and a custom rendered field, it works fine on first load, however, upon page refresh of the same dashboard, the following error occurs:
`cannot add a member with the name "renderedunlock" because a member with that name already exists`

This doesn't happen with a hashtable. I assume this is because add-member is being used to add to the object and probably needs -Force, or ideally the renderedunlock shouldn't be refreshed unless dynamic is specified or something.

Example of defining the custom rendered field:
`New-UDTableColumn -Property Unlock -Title "Action" -Render {'ok'}`
#### Version Information

- Universal: 1.3.0
- Universal Hosting Method (IIS, Executable, docker etc): Any
- PowerShell: Any
- Operating System: Any

### Workaround
`ConvertTo-Json | ConvertFrom-Json -AsHashtable` still works to mitigate this issue
#### Internal Issue

We'll fill this out when we create an internal issue in our repository.

**Comment by adamdriscoll** [comment]
Fixed in 1.4.7

**Comment by JustinGrote** [comment]
@adamdriscoll FYI I'm still seeing this pretty consistently after the second or third refresh of the page (rarely if ever seems to happen upon first load after startup). Should it be reopened or submitted as new issue?
![image](https://user-images.githubusercontent.com/15258962/103808279-984dd780-500c-11eb-9dec-c58954a5de17.png)

**Comment by adamdriscoll** [comment]
Are you running 1.5.8 of Universal? I thought we specifically added a -Force parameter onto that call to work around this.

**Comment by JustinGrote** [comment]
@adamdriscoll that was it, my bad, sorry to be "that user" :)

**Comment by crypticsh** [comment]
Just ran into this today as well, same version.
